### ISSUE TITLE
Getting Started section targets cURL version not natively available on Debian

### ISSUE THREAD

**Issue by TKussel** [samply/beam#47]
The `--json` convenience option combining the method, content type headers, and data flag was introduced in cURL version 7.82.0. However, Debian only ships cURL 7.74.0, so the Getting Started should refrain from using it and mention all parameters.

**Comment by lablans** [comment]
This will become a non-issue once curl is updated in the relevant distributions (e.g. bookworm in Debian). Would leave `--json` in. Instead, the documentation should give a quick note that the following commands require curl >= VERSION.

**Comment by TKussel** [comment]
Done in 3c3d56d
