### ISSUE TITLE
Optimize Certificate Cache usage

### ISSUE THREAD

**Issue by TKussel** [samply/beam#88]
Currently, all newly retrieved certificates are tested for validity. As invalid (i.e., expired) certificates are not stored, they are retrieved and checked in every update operation. This can be optimized by managing a blacklist of certificates, that are dropped without further processing. Furthermore, the amount of queries to the central CA might have room for improvement.

**Comment by lablans** [comment]
Would rather tell the underlying CA to forget expired certificate. This is supported in Hashicorp Vault, see https://developer.hashicorp.com/vault/api-docs/secret/pki#configure-automatic-tidy

**Comment by lablans** [comment]
Fixed in #106
